const PRODUCTS = [
  // ----- Greenhouse (GH) Range -----
  {
    id: "gh-fruit-loops",
    name: "Fruit Loops",
    range: "GH Bud",
    type: "Hybrid",
    thc: "18–21%",
    desc: "A flavour-packed hybrid that brings together vibrant aroma and balanced effects in every puff. Gentle, feel-good high that keeps your mind uplifted and body at ease.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-gelato-bliss",
    name: "Gelato Bliss",
    range: "GH Bud",
    type: "Hybrid",
    thc: "23–26%",
    desc: "A premium greenhouse-grown hybrid known for its deliciously sweet flavour and perfectly balanced effects. Euphoric highs, mellow body relaxation, rich creamy smoke.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-gorilla-klap",
    name: "Gorilla Klap",
    range: "GH Bud",
    type: "Indica",
    thc: "22–25%",
    desc: "A potent greenhouse-grown indica that packs a punch. Slow-building body high that hits heavy and lasts long. Melt away stress and ease physical tension.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-durban-poison",
    name: "Durban Poison",
    range: "GH Bud",
    type: "Sativa",
    thc: "19–22%",
    desc: "A legendary pure sativa known for its clear-headed, energetic high and sharp sweet aroma. Stay productive, inspired and socially engaged from sunrise to sundown.",
    pricePerG: 60,
    preRoll: 65,
    tag: "Greenhouse",
  },
  {
    id: "gh-cheeky-sunset",
    name: "Cheeky Sunset",
    range: "GH Bud",
    type: "Hybrid",
    thc: "22–24%",
    desc: "A well-balanced hybrid crafted for golden-hour vibes. Smooth, flavour-forward experience that uplifts your mood while easing the body into calm relaxation.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-cheese",
    name: "Cheese",
    range: "GH Bud",
    type: "Hybrid",
    thc: "22–25%",
    desc: "A classic with a twist — a balanced hybrid that delivers pungent flavour, smooth smoke and feel-good effects that hit just right, any time of day.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-royal-stank",
    name: "Royal Stank",
    range: "GH Bud",
    type: "Hybrid",
    thc: "20–21%",
    pack: "3G Tub",
    desc: "Bold character in a fresh 3G tub. Pungent, skunky aroma with earthy-sweet undertones. A smooth, steady high that blends uplifting clarity with relaxing ease.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-flat-bush-zombie",
    name: "Flat Bush Zombie",
    range: "GH Bud",
    type: "Indica",
    thc: "17–20%",
    desc: "A laid-back indica crafted for pure end-of-day bliss. Smooth, mellow high that calms the mind and relaxes the body without overpowering sedation.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-cedar-soul",
    name: "Cedar Soul",
    range: "GH Bud",
    type: "Indica",
    thc: "18–22%",
    desc: "Earthy, calming and deeply grounding. A soulful indica that relaxes the body while keeping the mind mellow and clear. Perfect for introspective evenings.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-coma-cookie",
    name: "Coma Cookie",
    range: "GH Bud",
    type: "Indica",
    thc: "19–24%",
    pack: "25G / 50G",
    desc: "Sweet, cookie-like flavours balanced by earthy undertones for a smooth, relaxing smoke. Unwind into deep, restful sleep.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-funk-gas",
    name: "Funk Gas",
    range: "GH Bud",
    type: "Sativa",
    thc: "18–20%",
    desc: "Pungent, energising and flavour-packed. A bold fuel-forward aroma balanced by subtle citrus notes. Clear-headed cerebral high that boosts energy and focus.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-amaretto",
    name: "Amaretto",
    range: "GH Bud",
    type: "Sativa",
    thc: "18–22%",
    desc: "Sweet, nutty and uplifting. Smooth almond-like flavour with bright, energising effects. Clear-headed cerebral high that sparks creativity and focus.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-code-red",
    name: "Code Red",
    range: "GH Bud",
    type: "Hybrid",
    thc: "18–22%",
    desc: "Bold, smooth and well-balanced. Sweet berry notes layered over subtle earthy undertones. Uplifting cerebral buzz paired with mellow body relaxation.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-jamaican-wedding",
    name: "Jamaican Wedding",
    range: "GH Bud",
    type: "Sativa",
    thc: "18–22%",
    desc: "Tropical, uplifting and smooth. Sweet fruity flavours layered over subtle earthy undertones. Clear-headed, energising high that sparks creativity.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-blueberry-snow-cone",
    name: "Blueberry Snow Cone",
    range: "GH Bud",
    type: "Hybrid",
    thc: "21–24%",
    desc: "Fruity, frosty and refreshing. Bold blueberry flavour with a sweet, icy finish. Uplifting cerebral high balanced by smooth body relaxation.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-tulips",
    name: "Tulips",
    range: "GH Bud",
    type: "Hybrid",
    thc: "20–22%",
    desc: "Floral, smooth and balanced. Delicate floral notes layered over earthy sweetness. Mellow cerebral lift paired with calming body effects.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-blue-diesel",
    name: "Blue Diesel",
    range: "GH Bud",
    type: "Hybrid",
    thc: "22–25%",
    desc: "Sweet meets diesel. A fruity berry profile with a bold fuel-like kick. Uplifting cerebral buzz alongside smooth body relaxation. A versatile favourite.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-reggae-romance",
    name: "Reggae Romance",
    range: "GH Bud",
    type: "Sativa",
    thc: "20–25%",
    pack: "3G Tub",
    desc: "Bring the vibes. An uplifting, social high with smooth flavour and cheerful energy that lasts. Perfect for creative flow and daytime adventures.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },
  {
    id: "gh-red-nuts",
    name: "Red Nuts",
    range: "GH Bud",
    type: "Indica",
    thc: "19–21%",
    pack: "3G Tub",
    desc: "Earthy, nutty and soothing. Calming body relaxation and a mellow high that eases stress without heavy sedation. Perfect for a moment of calm.",
    pricePerG: 50,
    preRoll: 55,
    tag: "Greenhouse",
  },

  // ----- Indoor (TGC) Range -----
  {
    id: "in-dough-z",
    name: "Dough-Z",
    range: "Indoor Bud",
    type: "Indica",
    thc: "25–28%",
    grade: "AAA",
    desc: "Top-tier indoor-grown indica crafted for bold flavour and powerful effects. Deeply calming full-body high, perfect for unwinding or a restful night.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-emerald-crisp",
    name: "Emerald Crisp",
    range: "Indoor Tub",
    type: "Indica",
    thc: "24–27%",
    grade: "AAA",
    desc: "Premium indoor-grown indica with a clean, crisp flavour profile. Calming full-body high that melts away stress. Perfect for evening sessions.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-dirty-diesel",
    name: "Dirty Diesel",
    range: "Indoor Bud",
    type: "Sativa",
    thc: "23–26%",
    grade: "AAA",
    desc: "High-potency indoor-grown sativa for energetic, creative highs with a bold flavour punch. Sharpens focus and lifts your mood for daytime use.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-banana-gas",
    name: "Banana Gas",
    range: "Indoor Bud",
    type: "Indica",
    thc: "25–28%",
    grade: "AAA",
    desc: "Top-shelf indoor indica combining sweet tropical flavour with knockout potency. Calming body buzz perfect for late-night sessions and stress relief.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-gas-station",
    name: "Gas Station",
    range: "Indoor Bud",
    type: "Hybrid",
    thc: "20–24%",
    grade: "AAA",
    desc: "Bold, gassy hybrid that balances mind and body with ease. Smooth, flavour-packed smoke offering a well-rounded high, perfect any time of day.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-velvet-truffle",
    name: "Velvet Truffle",
    range: "Indoor Tub",
    type: "Indica",
    thc: "22–25%",
    grade: "AAA",
    desc: "Silky, rich and irresistibly smooth. A luxurious indoor-grown indica that wraps the body in calm while easing the mind into pure tranquillity.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-frost-bite-delight",
    name: "Frost Bite Delight",
    range: "Indoor Bud",
    type: "Indica",
    thc: "20–23%",
    grade: "AAA",
    desc: "Premium indoor-grown indica for deep relaxation with a refreshingly smooth finish. Crisp mint-forward flavour layered with sweet berry notes.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-jax-palace",
    name: "Jax Palace",
    range: "Indoor Bud",
    type: "Hybrid",
    thc: "24–27%",
    grade: "AAA",
    desc: "Top-shelf indoor-grown hybrid with royal flavour and a high fit for a king. Uplifting the mind while melting tension from the body.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-nitro-boost",
    name: "Nitro Boost",
    range: "Indoor Bud",
    type: "Sativa",
    thc: "22–25%",
    grade: "AAA",
    desc: "High-octane indoor-grown sativa to energise your day and elevate your mindset. Fast-acting cerebral buzz that enhances focus and creativity.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-jungle-fever",
    name: "Jungle Fever",
    range: "Indoor Bud",
    type: "Indica",
    thc: "22–25%",
    grade: "AAA",
    desc: "Wild, rich and deeply relaxing. A potent indoor-grown indica offering full-body calm with exotic flavour. Smooth, sedating high for evening sessions.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-silky-souffle",
    name: "Silky Soufflé",
    range: "Indoor Bud",
    type: "Indica",
    thc: "22–24%",
    grade: "AAA",
    desc: "Smooth, decadent and deeply relaxing. A dessert-like flavour and a rich, calming high. Gentle sedation while quieting the mind for late-night chill.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-rocket-x",
    name: "Rocket X",
    range: "Indoor Bud",
    type: "Sativa",
    thc: "23–26%",
    grade: "AAA",
    desc: "High-powered indoor-grown sativa to elevate energy, sharpen focus and launch your day into overdrive. Fast-acting cerebral buzz for active adventures.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },
  {
    id: "in-stardust-seeker",
    name: "Stardust Seeker",
    range: "Indoor Bud",
    type: "Indica",
    thc: "20–21%",
    grade: "AA",
    desc: "Calming indoor-grown indica crafted for cosmic-level relaxation. Gentle, soothing high perfect for quiet evenings and winding down after a long day.",
    pricePerG: 120,
    preRoll: 125,
    tag: "Indoor",
  },

  // ----- Edibles -----
  {
    id: "ed-gummy-bears",
    name: "Dank Gummy Bears",
    range: "Edibles",
    type: "Hybrid",
    thc: "10mg / piece",
    pack: "20-pack",
    desc: "Chewy, fruit-flavoured gummy bears infused with premium distillate. Smooth, long-lasting effects — start with one and wait an hour.",
    pricePerG: null,
    price: 180,
    tag: "Edibles",
  },
  {
    id: "ed-choc-bar",
    name: "Cosmic Chocolate Bar",
    range: "Edibles",
    type: "Hybrid",
    thc: "100mg total",
    pack: "10 squares",
    desc: "Silky milk chocolate divided into 10 doseable squares. Balanced, body-melting relaxation wrapped in a rich, sweet treat.",
    pricePerG: null,
    price: 220,
    tag: "Edibles",
  },
  {
    id: "ed-cookie",
    name: "Coma Cookies",
    range: "Edibles",
    type: "Indica",
    thc: "50mg / cookie",
    desc: "Soft-baked cookies with a heavy indica kick. Perfect for deep, restful nights and unwinding after a long day.",
    pricePerG: null,
    price: 65,
    tag: "Edibles",
  },
  {
    id: "ed-lemonade",
    name: "Zing Lemonade",
    range: "Edibles",
    type: "Sativa",
    thc: "25mg / bottle",
    pack: "250ml",
    desc: "Refreshing sparkling lemonade with an uplifting sativa infusion. Clear-headed, social energy in a chilled bottle.",
    pricePerG: null,
    price: 120,
    tag: "Edibles",
  },

  // ----- CBD -----
  {
    id: "cbd-oil",
    name: "Pure CBD Oil",
    range: "CBD",
    type: "CBD",
    thc: "<0.05% THC",
    pack: "1000mg / 30ml",
    desc: "Full-spectrum CBD oil for calm, clarity and recovery without the high. Measured dropper for easy daily dosing.",
    pricePerG: null,
    price: 350,
    tag: "CBD",
  },
  {
    id: "cbd-gummies",
    name: "CBD Relief Gummies",
    range: "CBD",
    type: "CBD",
    thc: "0% THC",
    pack: "30-pack",
    desc: "THC-free wellness gummies for everyday balance and tension relief. Tasty, discreet and perfect for on-the-go calm.",
    pricePerG: null,
    price: 240,
    tag: "CBD",
  },
  {
    id: "cbd-balms",
    name: "Cool CBD Balm",
    range: "CBD",
    type: "CBD",
    thc: "0% THC",
    pack: "500mg / 50ml",
    desc: "Soothing topical balm for muscles and joints. Calming menthol finish with targeted, non-intoxicating relief.",
    pricePerG: null,
    price: 200,
    tag: "CBD",
  },
  {
    id: "cbd-flower",
    name: "CBD Flower (Lifter)",
    range: "CBD",
    type: "CBD",
    thc: "0.3% THC",
    pack: "3G",
    desc: "Mild, earthy hemp flower rich in CBD. Smooth, clear-headed sessions with minimal intoxication — great for daytime wellness.",
    pricePerG: null,
    price: 150,
    tag: "CBD",
  },
];

const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "Greenhouse", label: "Greenhouse" },
  { id: "Indoor", label: "Indoor" },
  { id: "Edibles", label: "Edibles" },
  { id: "CBD", label: "CBD" },
];
